export {default as Apple} from "./apple.svg"
export {default as Facebook} from "./facebook.svg"
export {default as Github} from "./github.svg"
export {default as Google} from "./google.svg"
export {default as Twitter} from "./twitter.svg"
export {default as Mail} from "./mail.svg"
export {default as Search} from "./search.svg"